### ISSUE TITLE
Doesn't run

### ISSUE THREAD

**Issue by EsenkayShady** [OrBaruk/HoneyMapping#1]
Hi, trying to ru this project after i clone but Its not running,

this is the error
<code>
shell@shell:~/Desktop/HoneyMapping$ python manage.py runserver 127.0.0.1:8000
Performing system checks...

Unhandled exception in thread started by <function wrapper at 0x7fc83cc085f0>
Traceback (most recent call last):
  File "/home/shell/.local/lib/python2.7/site-packages/django/utils/autoreload.py", line 228, in wrapper
    fn(*args, **kwargs)
  File "/home/shell/.local/lib/python2.7/site-packages/django/core/management/commands/runserver.py", line 125, in inner_run
    self.check(display_num_errors=True)
  File "/home/shell/.local/lib/python2.7/site-packages/django/core/management/base.py", line 359, in check
    include_deployment_checks=include_deployment_checks,
  File "/home/shell/.local/lib/python2.7/site-packages/django/core/management/base.py", line 346, in _run_checks
    return checks.run_checks(**kwargs)
  File "/home/shell/.local/lib/python2.7/site-packages/django/core/checks/registry.py", line 81, in run_checks
    new_errors = check(app_configs=app_configs)
  File "/home/shell/.local/lib/python2.7/site-packages/django/core/checks/urls.py", line 16, in check_url_config
    return check_resolver(resolver)
  File "/home/shell/.local/lib/python2.7/site-packages/django/core/checks/urls.py", line 26, in check_resolver
    return check_method()
  File "/home/shell/.local/lib/python2.7/site-packages/django/urls/resolvers.py", line 254, in check
    for pattern in self.url_patterns:
  File "/home/shell/.local/lib/python2.7/site-packages/django/utils/functional.py", line 35, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/home/shell/.local/lib/python2.7/site-packages/django/urls/resolvers.py", line 405, in url_patterns
    patterns = getattr(self.urlconf_module, "urlpatterns", self.urlconf_module)
  File "/home/shell/.local/lib/python2.7/site-packages/django/utils/functional.py", line 35, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/home/shell/.local/lib/python2.7/site-packages/django/urls/resolvers.py", line 398, in urlconf_module
    return import_module(self.urlconf_name)
  File "/usr/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
  File "/home/shell/Desktop/HoneyMapping/MalwareMap/urls.py", line 1, in <module>
    from django.conf.urls import patterns, include, url
ImportError: cannot import name patterns
</code>

**Comment by OrBaruk** [comment]
Hey,

So this is a really old code and it seems to not work with newer versions of Django due to api changes.

Currently I don't have time to maintain this code but I suggest you try installing an older version, 1.7 or 1.8 are the ones that would be out around the time this was developed.

**Comment by EsenkayShady** [comment]
Alright Thanks
